### PR TITLE
General tidy

### PR DESCRIPTION
**Pull request by IanVaughan**
Hi, I don't know if you still want to maintain this, seen as its not changed in over two years!

But I've made a few tiny tidy ups :-
- removed unused/not-required files
- tests are now assertions
- added `KMLFile#save` for easy saving
- renamed `kml.rb` to `ruby_kml.rb` to match gem name

I'd like to have it hosed on [rubygems.org](www.rubygems.org), if you want to push that up then that's cool, otherwise I don't mind.

### CODE REVIEW

**Comment by schleyfox** [comment]
Thanks! I'll take a look at this as soon as I get a chance.  This project mostly reached a point where it did what it needed to do for me, so I've been kind of neglecting it.  It might be time to take an active interest in it again.

**Comment by schleyfox** [comment]
I merged it, I have no idea who owns the ruby_kml gem on rubygems, so I'll just let this be.

**Comment by IanVaughan** [comment]
Nice.

WRT [rubygems](http://rubygems.org/gems/ruby_kml), it seems you own it!?

**Comment by schleyfox** [comment]
I'm seeing that this guy: https://rubygems.org/profiles/Qichunren owns it.  Very strange.

**Comment by IanVaughan** [comment]
Ahh I see what's happened!
@Qichunren has forked and pushed to rubygems, and claimed the name!
Looking at rubygem [stats](https://rubygems.org/gems/ruby_kml/stats) the downloads started on 30th may, I started using this (forked) around the start of May, when I looked then at rubygems, it didnt exist, but I didnt want to "claim" the name, so I asked...!
So, shame... never mind!

**Comment by qichunren** [comment]
Very sorry for my inappropriate behavior. Some time ago, I found your ruby_kml project on github, but it did not host on rubygems.org. Everytime I have to manually install the gem on local machine. So I forked your repository, and pushed to rubygems.

Sorry, I have delete the gem on rubygems.org (gem yank ruby_kml -v 0.1.6 ). Thanks for your work.

---Update

I found the command "gem yank ruby_kml -v 0.1.6 " just  remove versions from rubyGems.org's index, not permanently. 

I followed this link: http://help.rubygems.org/kb/gemcutter/removing-a-published-rubygem
I will find a suitable way to solve the problem.

**Comment by schleyfox** [comment]
Not a problem.  I've been a shitty maintainer.  I found this gem abandoned about four years ago and took it over before basically abandoning it myself.  If either one of you wants to take control of it, I can update this repo to point to your fork and you can have the name on rubygems.  Otherwise, I can push out a new gem.

**Pull request merged**
